In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import nonlinear

In [3]:
est, true = nonlinear.main()

tensor(79.0253, grad_fn=<MulBackward0>) 1.0
tensor(79.0297, grad_fn=<MulBackward0>) 1.0
tensor(79.0400, grad_fn=<MulBackward0>) 1.0
tensor(79.0286, grad_fn=<MulBackward0>) 1.0
tensor(78.9753, grad_fn=<MulBackward0>) 1.0
tensor(78.8470, grad_fn=<MulBackward0>) 1.0
tensor(78.5558, grad_fn=<MulBackward0>) 1.0
tensor(77.9456, grad_fn=<MulBackward0>) 1.0
tensor(76.6839, grad_fn=<MulBackward0>) 1.0
tensor(74.1202, grad_fn=<MulBackward0>) 1.0
tensor(68.9338, grad_fn=<MulBackward0>) 1.0
tensor(58.7117, grad_fn=<MulBackward0>) 1.0
tensor(40.4251, grad_fn=<MulBackward0>) 1.0
tensor(15.9666, grad_fn=<MulBackward0>) 1.0
tensor(13.1584, grad_fn=<MulBackward0>) 1.0
tensor(12.9595, grad_fn=<MulBackward0>) 1.0
tensor(13.1476, grad_fn=<MulBackward0>) 1.0
tensor(12.5836, grad_fn=<MulBackward0>) 1.0
tensor(12.1943, grad_fn=<MulBackward0>) 1.0
tensor(11.4162, grad_fn=<MulBackward0>) 1.0
tensor(11.0980, grad_fn=<MulBackward0>) 1.0
tensor(10.9889, grad_fn=<MulBackward0>) 1.0
tensor(11.1346, grad_fn=<MulBack

/Users/valen/anaconda3/lib/python3.11/site-packages/scipy/linalg/_matfuncs.py:378: RuntimeWarning: overflow encountered in matmul
  eAw = eAw @ eAw


tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>) 100.0
tensor(nan, grad_fn=<MulBackward0>

In [ ]:
est

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [5]:
p = 0
n = 1000
d = 5
m = nonlinear.NotearsMLP(dims=[(p+1) * d, 30, 1], out_dims=d, bias=True)

In [6]:
m._bounds()

[(0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, 0),
 (0, None),
 (0, None)

In [4]:
est

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [5]:
true

array([[0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])