In [1]:
from src.data.dataset import Dataset
from src.utill.constraint import Constraint
from src.utill.WAgraph import WAgraph
from src.model.NOTEARS import NOTEARS
from src.trainer.trainer import Trainer
import numpy as np

In [2]:
observations = 3
variables = 2
times = 6
window = 4

In [3]:
cons = Constraint([], [], window, variables)

In [4]:
W = np.array([[]])
cons.constrainW(W)
W

array([], shape=(1, 0), dtype=float64)

In [5]:
cons = Constraint([[0,0,1], [1,0,3]], [[0,0,0,1]], window, variables)

In [6]:
W = np.array([[2, 2],[2, 2]])
cons.constrainW(W)
W

array([[1, 2],
       [3, 2]])

In [7]:
A = np.array([[[2], [2]],[[2], [2]]])
cons.constrainA(A)
A

array([[[1],
        [2]],

       [[2],
        [2]]])

In [8]:
cons.validate(window, variables)

True

In [9]:
WA = WAgraph(window, variables)

In [10]:
WA.getWindow()

4

In [11]:
WA.getV()

2

In [12]:
WA.getVA()

2

In [13]:
WA.setW([[2,2],[2,2]])
WA.getW()

array([[2, 2],
       [2, 2]])

In [14]:
WA.setA([[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]])
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [15]:
WA.generateW()

In [16]:
WA.getW()

array([[0.25099343, 0.94120467],
       [0.32823697, 0.11051276]], dtype=float32)

In [17]:
WA.generateW_B(1, 'ER')

2 1


In [18]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [19]:
WA.generateW()
WA.getW()

array([[0.        , 0.        ],
       [0.80591315, 0.        ]], dtype=float32)

In [20]:
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [21]:
WA.A_B

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int32)

In [22]:
WA.generateA()
WA.getA()

array([[[0.78658587, 0.2954582 ],
        [0.51598495, 0.18044259]],

       [[0.3299557 , 0.10373474],
        [0.37742004, 0.12933609]],

       [[0.6958986 , 0.83042663],
        [0.32942367, 0.60888517]],

       [[0.22294591, 0.45579883],
        [0.89648384, 0.41957185]]], dtype=float32)

In [23]:
WA.generateA_B(3, 'ER')

In [24]:
WA.A_B

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]]], dtype=torch.float64)

In [25]:
WA.generateA()
WA.getA()

array([[[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.13176513],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.74202824],
        [0.        , 0.        ]]])

In [26]:
WA.getA()

array([[[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.13176513],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.74202824],
        [0.        , 0.        ]]])

In [27]:
WA.getW()

array([[0.        , 0.        ],
       [0.80591315, 0.        ]], dtype=float32)

In [28]:
WA.getA()

array([[[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.13176513],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.74202824],
        [0.        , 0.        ]]])

In [29]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [30]:
WA.A_B

tensor([[[0, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 1],
         [0, 0]]], dtype=torch.int32)

In [31]:
from src.data.dataset import Dataset

In [32]:
ds = Dataset(observations, variables, variables, times, window, WA, cons)

In [33]:
dataex = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

ds.setData(dataex)

In [34]:
ds.getData()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [35]:
ds.getDataWindow()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [36]:
ds.getWA()

In [37]:
ds.generateData(lambda x: np.random.rand())

In [38]:
ds.data

array([[[5.90449478, 5.92138231, 6.76732506],
        [5.33953918, 3.6689769 , 5.23723274]],

       [[4.75965409, 4.80945224, 5.35541059],
        [2.08848429, 2.24018565, 3.30885701]],

       [[4.48906975, 4.06661602, 4.42403426],
        [2.48570468, 3.38137674, 3.77999915]],

       [[3.61569008, 2.52931432, 2.47203719],
        [1.18862651, 2.09943365, 1.43745573]],

       [[3.25297488, 1.51821841, 2.32181831],
        [3.86241942, 2.29567812, 1.59345099]],

       [[1.56211719, 0.26048906, 1.93026657],
        [2.23720437, 1.35746882, 3.76136733]]])

In [39]:
ds.WA.A

tensor([[[1.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.1318],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.7420],
         [0.0000, 0.0000]]], dtype=torch.float64)

In [40]:
ds.WA.W

tensor([[1., 0.],
        [3., 0.]])

In [41]:
ds.WA.getW()

array([[1., 0.],
       [3., 0.]], dtype=float32)

In [42]:
import math
pos = np.random.randint(0, (2*2-2)//2)
y = math.floor(.5*(np.sqrt(8*pos+9)))
x = pos-(y*(y-1)//2)
print(pos)
print(y)
print(x)

0
1
0


In [43]:
ds.WA.getW()[y][x]

3.0

In [44]:
WA.generateW_B(1, "ER")
WA.generateW()

2 1


In [45]:
WA.getW()

array([[0.        , 0.        ],
       [0.56888515, 0.        ]], dtype=float32)

In [46]:
WA.getW_B()

array([[0, 0],
       [1, 0]])

In [47]:
nt = NOTEARS(window, variables)

In [48]:
nt.set_learning_rate(1e-3)

In [49]:
nt.run(ds.data)

(tensor(10.2846, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(10.2846, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [50]:
nt.update(ds.data)

/Users/tylergibbs/dsc180/src/model/model.py:60: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


(tensor(10.2846, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(10.2846, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [51]:
nt.WA.W.grad

tensor([[-12.8581,  -9.8550],
        [ -9.8550,  -7.7112]])

In [109]:
WA = WAgraph(window, variables)
WA.generateW_B(1, 'ER')
WA.generateW()
WA.generateA_B(3, 'ER')
WA.generateA()

cons = Constraint([], [], window, variables)

ds = Dataset(observations, variables, variables, times, window, WA, cons)
ds.generateData(lambda x: np.random.rand())

nt = NOTEARS(window, variables, .1, .1, 10000)

tr = Trainer(.1)
tr.train(nt, ds.data, ds.data, 10000, 0, 1000)

2 1
TRAINING: [Iter 0] score 0.665051281452179, likelyhood 0.665051281452179, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0
(0, 'VALIDATION: [Iter 0] score 0.665051281452179, likelyhood 0.665051281452179, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0')
TRAINING: [Iter 1000] score 0.14548668265342712, likelyhood 0.027219083160161972, sparcityW 0.016960449516773224, sparcityA 1.1657155752182007, acyclicity 0.0
(1000, 'VALIDATION: [Iter 1000] score 0.13874801993370056, likelyhood 0.027219083160161972, sparcityW 0.016960449516773224, sparcityA 1.1657155752182007, acyclicity 0.0')
TRAINING: [Iter 2000] score 0.5202896595001221, likelyhood 0.026463091373443604, sparcityW 0.031502656638622284, sparcityA 1.1397494077682495, acyclicity 3.7670135498046875e-05
(2000, 'VALIDATION: [Iter 2000] score 0.5699046850204468, likelyhood 0.026463091373443604, sparcityW 0.031502656638622284, sparcityA 1.1397494077682495, acyclicity 3.7670135498046875e-05')
TRAINING: [Iter 3000] score 0.30676978826522827, like

In [110]:
nt.WA.getW()

array([[0.00186966, 0.00423277],
       [0.00457578, 0.00215315]], dtype=float32)

In [111]:
ds.WA.getW()

array([[0.        , 0.        ],
       [0.47100544, 0.        ]], dtype=float32)

In [112]:
nt.WA.getA().round(2)

array([[[ 0.  ,  0.03],
        [ 0.15,  0.75]],

       [[ 0.  ,  0.01],
        [-0.  ,  0.01]],

       [[ 0.01,  0.05],
        [-0.01,  0.02]],

       [[ 0.02, -0.  ],
        [ 0.05,  0.04]]], dtype=float32)

In [113]:
ds.WA.getA()

array([[[0.34848869, 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.60850728]],

       [[0.        , 0.72014058],
        [0.        , 0.        ]]])