In [40]:
from src.data.dataset import Dataset
from src.utill.constraint import Constraint
from src.utill.WAgraph import WAgraph
import numpy as np

In [41]:
observations = 3
variables = 2
times = 6
window = 4

In [42]:
cons = Constraint([], [], window, variables)

In [43]:
W = np.array([[]])
cons.constrainW(W)
W

array([], shape=(1, 0), dtype=float64)

In [44]:
cons = Constraint([[0,0,1], [1,0,3]], [[0,0,0,1]], window, variables)

In [45]:
W = np.array([[2, 2],[2, 2]])
cons.constrainW(W)
W

array([[1, 2],
       [3, 2]])

In [46]:
A = np.array([[[2], [2]],[[2], [2]]])
cons.constrainA(A)
A

array([[[1],
        [2]],

       [[2],
        [2]]])

In [47]:
cons.validate(window, variables)

True

In [48]:
WA = WAgraph(window, variables)

In [49]:
WA.getWindow()

4

In [50]:
WA.getV()

2

In [51]:
WA.getVA()

2

In [52]:
WA.setW([[2,2],[2,2]])
WA.getW()

array([[2, 2],
       [2, 2]])

In [53]:
WA.setA([[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]])
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [54]:
WA.generateW()

In [55]:
WA.getW()

array([[0.10333531, 0.44171465],
       [0.04101156, 0.39531893]])

In [56]:
WA.generateW_B(1, 'ER')

In [57]:
WA.W_B

array([[0., 0.],
       [0., 1.]])

In [58]:
WA.generateW()
WA.getW()

array([[0.        , 0.        ],
       [0.        , 0.71794586]])

In [59]:
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [60]:
WA.A_B

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [61]:
WA.generateA()
WA.getA()

array([[[0.92240732, 0.6862707 ],
        [0.68375447, 0.08232078]],

       [[0.89892365, 0.74524802],
        [0.62144161, 0.38430805]],

       [[0.35158324, 0.26513008],
        [0.01483125, 0.87254128]],

       [[0.12377053, 0.12081559],
        [0.21107919, 0.02047898]]])

In [62]:
WA.generateA_B(3, 'ER')

In [63]:
WA.A_B

array([[[1., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.]]])

In [64]:
WA.generateA()
WA.getA()

array([[[0.34568258, 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.32972594],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.05370134]]])

In [65]:
WA.getA()

array([[[0.34568258, 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.32972594],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.05370134]]])

In [66]:
WA = cons.constrainWA(WA)

In [67]:
WA.getW()

array([[1.        , 0.        ],
       [3.        , 0.71794586]])

In [68]:
WA.getA()

array([[[1.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.32972594],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.05370134]]])

In [69]:
WA.W_B

array([[1, 0],
       [1, 1]])

In [70]:
WA.A_B

array([[[1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 1],
        [0, 0]],

       [[0, 0],
        [0, 1]]])

In [71]:
from src.data.dataset import Dataset

In [72]:
ds = Dataset(observations, variables, variables, times, window, WA, cons)

In [73]:
dataex = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

ds.setData(dataex)

(6, 2, 3)


In [74]:
ds.getData()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [75]:
ds.getDataWindow()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [76]:
ds.getWA()

In [77]:
ds.generateData(lambda x: np.random.rand())

(2, 3) (2, 3) (2, 3)
(2, 3) (2, 3) (2, 3)
(2, 3) (2, 3) (2, 3)
(2, 3) (2, 3) (2, 3)
(2, 3) (2, 3) (2, 3)
(2, 3) (2, 3) (2, 3)
(6, 2, 3)


In [79]:
ds.data

array([[[0.83099257, 0.14448427, 0.03457177],
        [0.4207793 , 0.3529993 , 0.66056809]],

       [[0.88192029, 0.91958093, 0.73491666],
        [0.82898865, 0.58349516, 0.0354362 ]],

       [[0.91888084, 0.35323469, 0.76332255],
        [0.99116645, 0.24697949, 0.85975362]],

       [[0.12669097, 0.44054006, 0.22414773],
        [0.98903446, 0.71254874, 0.71117547]],

       [[4.11503038, 2.53486897, 2.97166245],
        [1.56119375, 0.75121402, 1.81575742]],

       [[2.968855  , 1.60839599, 3.47998736],
        [1.13767637, 0.21596771, 2.75032952]]])

In [80]:
ds.WA.A

array([[[1.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.32972594],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.05370134]]])

In [81]:
ds.WA.W

array([[1.        , 0.        ],
       [3.        , 0.71794586]])