In [1]:
import numpy as np
import scipy.linalg as sla
import numpy.linalg as la
from scipy.special import expit as sigmoid
import scipy as sc
from statsmodels.tsa.api import VAR

In [2]:
varables = 3
observations = 1400
window = 2
#to use later 
times = 5

In [3]:
def qDag(w):
    return np.trace(sc.linalg.expm(np.multiply(w,w))) - w.shape[0]
def get_r(off):
    return lambda n: np.random.rand(n)+off

In [4]:
dagY = sc.sparse.random(varables, varables*window, density=0.15, data_rvs=get_r(.5)).A

dagX = np.eye(varables, varables)
while qDag(dagX) != 0:
    dagX = sc.sparse.random(varables, varables, density=0.25, data_rvs=get_r(.5)).A
    np.fill_diagonal(dagX, 0)

In [5]:
print(qDag(dagX))
print(dagX)
print(dagY)

0.0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.         0.         0.         0.         1.30085601 0.        ]
 [0.         0.         0.         0.         1.17672539 0.        ]
 [0.         0.         0.         0.         0.         1.3019802 ]]


In [6]:
def rand(n):
    return 2*(np.random.rand(n)-.5)

Y_pre = rand(observations*varables*window).reshape(varables*window, observations)
print(dagY.shape)
print(Y_pre.shape)

(3, 6)
(6, 1400)


In [7]:
#X = XW + YA + Z

def randFlat(X):
    return rand(X.shape[0]*X.shape[1]).reshape(*X.shape)

def onesFlat(X):
    return np.ones(X.shape[0]*X.shape[1]).reshape(*X.shape)

def update(preY, preX, dagY, dagX, rand):
    Xy = np.matmul(dagY, preY)
    Xr = rand(preX)
    Xx = np.matmul(dagX, Xr)
    X = Xr + Xx + Xy
    
    return X

def step(preY, dagY, dagX, window, var, rand):
    preX = preY[:var]
    preY = preY[:window*var]
    return update(preY, preX, dagY, dagX, rand)

def makeSynthData(preY, times, obs, var, pad, rand=rand):
    window = preY.shape[0]//var
    
    for i in range(pad+window):
        newX = step(preY, dagY, dagX, window, var, rand)
        preY = np.append(newX, preY, axis=0)

    Y = preY[:window*var]

    for i in range(times - window):
        newX = step(Y, dagY, dagX, window, var, rand)
        Y = np.append(newX, Y, axis=0)
        
    return Y
    



#later
#W = np.random.rand(varables*observations).reshape(varables,observations)

In [8]:
Y_pre = np.ones(observations*varables*window).reshape(varables*window, observations)
XY = makeSynthData(Y_pre, times, observations, varables, 0, randFlat)
Y=XY[varables:window*varables+varables]
X=XY[:varables]

In [9]:
XY

array([[ 1.17935877,  2.92260449,  0.79206399, ...,  0.34848473,
         0.65044804,  0.55829036],
       [ 0.8892889 ,  3.35678895, -0.48036689, ...,  0.96851937,
         0.75684426,  0.60911529],
       [ 1.50159501,  0.75895606,  2.5779033 , ...,  2.66987767,
         1.60855055,  3.9544985 ],
       ...,
       [ 1.10650573,  1.63036964,  0.38819942, ...,  0.55721546,
         1.55229641,  0.35480269],
       [ 0.62718825,  1.89699343,  0.76533771, ...,  1.50440386,
         0.7033205 ,  0.32746225],
       [ 0.71724142,  1.33014029,  0.76061045, ...,  1.33302255,
         0.36581781,  1.96092579]])

In [10]:
C_init = np.random.rand(varables*varables*window + varables*varables)

In [11]:
def f_DYNOTEARS(X, Y, lA, lB):
    def aux(C):
        a = C[:varables*window*varables].reshape(varables, varables*window)
        w = C[varables*window*varables:].reshape(varables, varables)
    
        loss = np.square(
                np.linalg.norm(
                    np.matmul(np.eye(varables, varables) - w, X)
                    - np.matmul(a, Y)
                    , "fro"
                )
            )/np.prod(X.shape)
        #print(loss)
        return loss + lB*np.linalg.norm(w.flatten(), 1) + lA*np.linalg.norm(a.flatten(), 1) 
    return aux

In [12]:
def constr_DYNOTEARS(C):
    w = C[varables*window*varables:].reshape(varables, varables)
    return qDag(w)

cons = {'type':'eq', 'fun': constr_DYNOTEARS}

C = sc.optimize.minimize(f_DYNOTEARS(X,Y,.1,.1) , C_init, constraints=cons).x

In [13]:
A = C[:varables*window*varables].reshape(varables, varables*window)
W = C[varables*window*varables:].reshape(varables, varables)
np.fill_diagonal(W, 0)

In [14]:
A.round(1)

array([[ 0. , -0. ,  0. ,  0. ,  1.2,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.9, -0. ],
       [-0. ,  0. ,  0. ,  0. ,  0. ,  1.3]])

In [15]:
dagY.round(1)

array([[0. , 0. , 0. , 0. , 1.3, 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.3]])

In [16]:
W.round(1)

array([[0. , 0. , 0. ],
       [0.1, 0. , 0. ],
       [0. , 0. , 0. ]])

In [17]:
dagX.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
dagX.T.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
def H1ldet(W):
    det = np.linalg.det(np.eye(W.shape[0]) - np.multiply(W,W))
    if (det <= 0):
        print(det)
    return -np.log(det)

def constr_DAGMA(C):
    w = C[varables*window*varables:].reshape(varables, varables)
    return H1ldet(w)

A_init = np.random.rand(varables*varables*window)

W_init = np.random.rand(varables*varables).reshape(varables, varables)
np.fill_diagonal(W_init, 0)
while H1ldet(W_init) is np.nan:
    W_init = np.random.rand(varables*varables).reshape(varables, varables)
    np.fill_diagonal(W, 0)

C_init = np.append(A_init, W_init.reshape(varables*varables), axis = 0)

cons = {'type':'eq', 'fun': constr_DAGMA}

#C = sc.optimize.minimize(f_DYNOTEARS(X,Y,.01,.1) , C_init, constraints=cons).x

In [20]:
A = C[:varables*window*varables].reshape(varables, varables*window)
W = C[varables*window*varables:].reshape(varables, varables)
np.fill_diagonal(W, 0)

In [21]:
A[A<.3] = 0
A.round()

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
dagY.round()

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
W.round(1)

array([[0. , 0. , 0. ],
       [0.1, 0. , 0. ],
       [0. , 0. , 0. ]])

In [24]:
dagX.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
dagX.T.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
C_init = np.random.rand(varables*varables*window + varables*varables)
H1ldet(C_init.T)

-11.879904709149997


/var/folders/z_/p0tz320d6j13q0rkv_f35brm0000gn/T/ipykernel_5998/3164180601.py:5: RuntimeWarning: invalid value encountered in log
  return -np.log(det)


nan

In [27]:
def metrics(A,dagY, W, dagX):
    A = np.absolute(A) > 0.3
    dagY = np.absolute(dagY) > .5
    W = np.absolute(W) > 0.3
    dagX = np.absolute(dagX) > .5
    
    preWrong = A != dagY
    wWrong = W != dagX
    #assumes cant be both wrong and inv
    wInverse = W.T & dagX
    
    if ((W + W.T)==2).any():
        print(W)
        print(W.T)
        raise "error"
    
    #print(A)
    #print(dagY)
    #print(W)
    #print(dagX)
    #print()
    #print(preWrong)
    #print(wWrong)
    #print(wInverse)
    
    return {
        "preWrong": sum(sum(preWrong)),
        "wWrong": sum(sum(wWrong)),
        "wInverse": sum(sum(wInverse))
    }
    

In [28]:
metrics(A,dagY, W, dagX)

{'preWrong': 0, 'wWrong': 0, 'wInverse': 0}

In [29]:
A.round()

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
dagY.round()

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.matmul(np.eye(varables, varables) - W, X).round(1)

array([[ 1.2,  2.9,  0.8, ...,  0.3,  0.6,  0.5],
       [ 0.7,  3. , -0.6, ...,  0.9,  0.7,  0.5],
       [ 1.5,  0.8,  2.6, ...,  2.7,  1.6,  4. ]])

In [32]:
def transformTimeData(data, window, times):
    variables = data.shape[0]//times
    print(data.shape[0]/times)
    
    snapshots = times - window - 1
    
    ret = []
    
    for i in range(snapshots):
        slic = data[i*variables:i*variables+(window+1)*variables]
        ret.append( slic)
    
    return np.hstack(ret)
    
    

In [33]:
XY_stack = transformTimeData(XY, window, times)

3.0


In [34]:
Y_stack=XY_stack[varables:window*varables+varables]
X_stack=XY_stack[:varables]


In [35]:
print(XY.shape)
print(XY_stack.shape)
print(Y_stack.shape)
print(X_stack.shape)

(15, 1400)
(9, 2800)
(6, 2800)
(3, 2800)


In [36]:
XY.shape

(15, 1400)

In [37]:
XY_stack

array([[ 1.17935877,  2.92260449,  0.79206399, ...,  2.18443312,
         1.14069776,  1.99290645],
       [ 0.8892889 ,  3.35678895, -0.48036689, ...,  1.38448885,
         1.78689043,  1.41263155],
       [ 1.50159501,  0.75895606,  2.5779033 , ...,  1.97829766,
         1.98111648,  2.10515377],
       ...,
       [ 1.03292439,  1.68034946,  0.00883593, ...,  0.47336915,
         1.9493571 ,  2.27210968],
       [ 0.74110933,  2.66631522,  0.16881287, ...,  1.7604751 ,
         1.64227296,  1.21854964],
       [ 0.38815249,  1.04807568,  1.83133307, ...,  1.47358585,
         1.89823389,  2.28869475]])

In [38]:
X_stack

array([[ 1.17935877,  2.92260449,  0.79206399, ...,  2.18443312,
         1.14069776,  1.99290645],
       [ 0.8892889 ,  3.35678895, -0.48036689, ...,  1.38448885,
         1.78689043,  1.41263155],
       [ 1.50159501,  0.75895606,  2.5779033 , ...,  1.97829766,
         1.98111648,  2.10515377]])

In [39]:
Y_stack

array([[ 1.85306541,  2.22578273,  1.22880035, ...,  2.04796991,
         0.82643243, -0.23647527],
       [ 1.59259503,  3.06315904,  0.0063249 , ...,  1.01596128,
         0.24294599,  0.68515417],
       [ 2.77422852,  0.37128611,  0.20332439, ...,  2.61747433,
         1.42626989,  2.48060886],
       [ 1.03292439,  1.68034946,  0.00883593, ...,  0.47336915,
         1.9493571 ,  2.27210968],
       [ 0.74110933,  2.66631522,  0.16881287, ...,  1.7604751 ,
         1.64227296,  1.21854964],
       [ 0.38815249,  1.04807568,  1.83133307, ...,  1.47358585,
         1.89823389,  2.28869475]])

In [40]:
cons = {'type':'eq', 'fun': constr_DYNOTEARS}
C = sc.optimize.minimize(f_DYNOTEARS(X_stack,Y_stack,.01,.1) , C_init, constraints=cons).x

In [41]:
A = C[:varables*window*varables].reshape(varables, varables*window)
W = C[varables*window*varables:].reshape(varables, varables)
np.fill_diagonal(W, 0)

In [42]:
abs(A.round(1))

array([[0. , 0. , 0. , 0. , 1.3, 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.3]])

In [43]:
dagY.round(1)

array([[0. , 0. , 0. , 0. , 1.3, 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.3]])

In [44]:
W.round(2)

array([[ 0.,  0., -0.],
       [-0.,  0., -0.],
       [ 0.,  0.,  0.]])

In [45]:
dagX.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
dagX.T.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
#tensor representation for timeseries
dagYtesnor = np.transpose(np.array([dagY[:,i*varables:(i+1)*varables] for i in range(window)]),(0,2,1))

dagXtesnor = dagX
print(dagYtesnor.round().shape)

XYtesnor = XY.reshape(times, varables, observations)
print(XYtesnor.shape)

(3, 3, 3)
(5, 3, 1000)


In [96]:
XYtesnor

array([[[ 2.83500155,  4.20864923,  0.42673679, ...,  2.46287197,
          2.9860356 ,  3.30613402],
        [ 2.75849403,  8.81301775,  3.57803976, ...,  5.55809189,
          7.63826809,  8.64164758],
        [ 0.85999844,  2.75991344,  0.9639159 , ...,  1.20194524,
          2.23853415,  2.76316412]],

       [[ 0.38218448,  3.14961631,  2.6886667 , ...,  2.62572707,
          3.26591988,  4.45719049],
        [ 3.68976684,  8.31865416,  6.62324037, ...,  6.51463553,
          6.5383516 ,  5.01291413],
        [ 0.9784015 ,  2.35396331,  1.9027565 , ...,  1.75081257,
          1.97042291,  1.67288918]],

       [[ 1.19289768,  4.07220971,  3.08801754, ...,  3.83001853,
          2.16994063,  1.3538501 ],
        [ 2.96825265,  5.55042407,  1.7040868 , ...,  5.35436684,
          3.58454102,  2.20002415],
        [ 1.02323495,  2.06963608,  0.20600265, ...,  2.06390986,
          0.97640408,  0.74006252]],

       [[ 2.06103529,  1.56038318, -0.79048064, ...,  1.52507037,
          

In [98]:
XY.reshape(times*varables, observations)

array([[ 2.83500155,  4.20864923,  0.42673679, ...,  2.46287197,
         2.9860356 ,  3.30613402],
       [ 2.75849403,  8.81301775,  3.57803976, ...,  5.55809189,
         7.63826809,  8.64164758],
       [ 0.85999844,  2.75991344,  0.9639159 , ...,  1.20194524,
         2.23853415,  2.76316412],
       ...,
       [-0.34501874,  2.0993673 ,  1.10717453, ...,  1.97264966,
         1.52271318,  2.01855854],
       [ 1.75953088,  3.23472843,  3.39184166, ...,  3.27247628,
         3.73409344,  2.89941241],
       [ 0.44297904,  1.70041776,  1.55385091, ...,  1.18032598,
         1.31506505,  1.24818192]])

In [49]:
Y_stack=XY_stack[varables:window*varables+varables]
X_stack=XY_stack[:varables]

In [50]:
Y_stack

array([[ 1.85306541,  2.22578273,  1.22880035, ...,  2.04796991,
         0.82643243, -0.23647527],
       [ 1.59259503,  3.06315904,  0.0063249 , ...,  1.01596128,
         0.24294599,  0.68515417],
       [ 2.77422852,  0.37128611,  0.20332439, ...,  2.61747433,
         1.42626989,  2.48060886],
       [ 1.03292439,  1.68034946,  0.00883593, ...,  0.47336915,
         1.9493571 ,  2.27210968],
       [ 0.74110933,  2.66631522,  0.16881287, ...,  1.7604751 ,
         1.64227296,  1.21854964],
       [ 0.38815249,  1.04807568,  1.83133307, ...,  1.47358585,
         1.89823389,  2.28869475]])

In [51]:
X_stack

array([[ 1.17935877,  2.92260449,  0.79206399, ...,  2.18443312,
         1.14069776,  1.99290645],
       [ 0.8892889 ,  3.35678895, -0.48036689, ...,  1.38448885,
         1.78689043,  1.41263155],
       [ 1.50159501,  0.75895606,  2.5779033 , ...,  1.97829766,
         1.98111648,  2.10515377]])

In [52]:
def diff(X, w, a):
    X_check = X[:X.shape[0]-a.shape[0]]
    
    Xw = np.matmul(w, X_check)
    #print(a.shape)
    #print(X.shape[0]-window+1)
    Xa = np.array([np.tensordot(a, X[i:i+window], axes=((0,1),(0,1)))
                    for i in range(1, X.shape[0]-window+1)])
    #print(X_check.shape)
    #print(Xw.shape)
    #print(Xa.shape)
    
    return X_check - Xw - Xa

def f_DYNOTEARS_TENSOR(X, lA, lB):
    def aux(C):
        a = C[:varables*window*varables].reshape(window, varables, varables)
        w = C[varables*window*varables:].reshape(varables, varables)
    
        loss = np.square(diff(X, w, a)).sum().sum().sum()/np.prod(X.shape)
        #print(loss)
        return loss + lB*np.linalg.norm(w.flatten(), 1) + lA*np.linalg.norm(a.flatten(), 1) 
    return aux

def ll(X, Y, w, a):
    return np.square(
                np.linalg.norm(
                    np.matmul(np.eye(varables, varables) - w, X)
                    - np.matmul(a, Y)
                    , "fro"
                )
            )/np.prod(X.shape)

In [53]:
Y_stack=XY_stack[varables:window*varables+varables]
X_stack=XY_stack[:varables]

In [54]:
def constr_DYNOTEARS(C):
    w = C[varables*window*varables:].reshape(varables, varables)
    return qDag(w)

cons = {'type':'eq', 'fun': constr_DYNOTEARS}

C = sc.optimize.minimize(f_DYNOTEARS_TENSOR(XYtesnor,.05,.05) , C_init, constraints=cons).x

In [55]:
A = C[:varables*window*varables].reshape(window, varables, varables)
W = C[varables*window*varables:].reshape(varables, varables)
print(ll(X_stack, Y_stack, dagX, dagY))

#print(ll(XYtesnor, W, A))

print(np.square(diff(XYtesnor, dagX, dagYtesnor)).sum().sum().sum()/np.prod(XYtesnor.shape))

print(np.square(diff(XYtesnor, W, A)).sum().sum().sum()/np.prod(XYtesnor.shape))

0.33105701969066226
0.19925244009939694
0.20427725021889526


In [56]:
A.shape

(2, 3, 3)

In [57]:
W.shape

(3, 3)

In [58]:
A.round(1)

array([[[ 0. ,  0. ,  0. ],
        [ 0. ,  0. , -0. ],
        [ 0. ,  0. ,  0. ]],

       [[ 0. ,  0. ,  0. ],
        [ 1.2,  1. ,  0. ],
        [ 0. ,  0. ,  1.3]]])

In [59]:
dagYtesnor.round(1)

array([[[0. , 0. , 0. ],
        [0. , 0. , 0. ],
        [0. , 0. , 0. ]],

       [[0. , 0. , 0. ],
        [1.3, 1.2, 0. ],
        [0. , 0. , 1.3]]])

In [60]:
XYtesnor[1:1+window].round()

array([[[ 2.,  2.,  1., ...,  2.,  1.,  2.],
        [ 2.,  3.,  0., ...,  1.,  2.,  1.],
        [ 3.,  0.,  0., ...,  2.,  2.,  2.]],

       [[ 1.,  2.,  0., ...,  2.,  1., -0.],
        [ 1.,  3.,  0., ...,  1.,  0.,  1.],
        [ 0.,  1.,  2., ...,  3.,  1.,  2.]]])

In [61]:
dagYtesnor.round(1)

array([[[0. , 0. , 0. ],
        [0. , 0. , 0. ],
        [0. , 0. , 0. ]],

       [[0. , 0. , 0. ],
        [1.3, 1.2, 0. ],
        [0. , 0. , 1.3]]])

In [62]:
np.tensordot(A, XYtesnor[1:1+window], axes=((0,1),(0,1))).round(1)

array([[0.9, 3.3, 0.2, ..., 1.3, 0.3, 0.8],
       [0.7, 2.6, 0.2, ..., 1. , 0.2, 0.7],
       [0.5, 1.3, 2.3, ..., 3.3, 1.8, 3.1]])

In [63]:
XYtesnor[0].round()
XYtesnor[1:1+window].round()

array([[[ 2.,  2.,  1., ...,  2.,  1.,  2.],
        [ 2.,  3.,  0., ...,  1.,  2.,  1.],
        [ 3.,  0.,  0., ...,  2.,  2.,  2.]],

       [[ 1.,  2.,  0., ...,  2.,  1., -0.],
        [ 1.,  3.,  0., ...,  1.,  0.,  1.],
        [ 0.,  1.,  2., ...,  3.,  1.,  2.]]])

In [64]:
#np.array([dagY[:,i*varables:(i+1)*varables] for i in range(window)]).round(1)

In [65]:
dagY.round(1)

array([[0. , 0. , 0. , 0. , 1.3, 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.3]])

In [66]:
Y_stack.round()

array([[ 2.,  2.,  1., ...,  2.,  1., -0.],
       [ 2.,  3.,  0., ...,  1.,  0.,  1.],
       [ 3.,  0.,  0., ...,  3.,  1.,  2.],
       [ 1.,  2.,  0., ...,  0.,  2.,  2.],
       [ 1.,  3.,  0., ...,  2.,  2.,  1.],
       [ 0.,  1.,  2., ...,  1.,  2.,  2.]])

In [67]:
np.matmul(dagY, Y_stack).round()

array([[1., 3., 0., ..., 2., 2., 2.],
       [1., 3., 0., ..., 2., 2., 1.],
       [1., 1., 2., ..., 2., 2., 3.]])

In [68]:
X_stack.round()

array([[ 1.,  3.,  1., ...,  2.,  1.,  2.],
       [ 1.,  3., -0., ...,  1.,  2.,  1.],
       [ 2.,  1.,  3., ...,  2.,  2.,  2.]])

In [69]:
dagX.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
W.round(1)

array([[0. , 0. , 0. ],
       [0.1, 0. , 0. ],
       [0. , 0. , 0. ]])

In [71]:
def get_sparse(X):
    ret = []
    for i in range(len(X)):
        for j in range(len(X[i])):
            val = X[i,j]
            if not np.isnan(val):
                print(val)
                ret.append((i, j, val))
    return ret

constraint_matrix_X = np.array(
[
    [np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan],
    [0, 1.1, np.nan],
])
X_set = np.logical_not(np.isnan(constraint_matrix_X)).sum().sum()
print(X_set)
X_sparce = get_sparse(constraint_matrix_X)

            
constraint_matrix_Y = np.array(
[
    [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan, 6, np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
])
Y_set = np.logical_not(np.isnan(constraint_matrix_Y)).sum().sum()
print(Y_set)
Y_sparce = get_sparse(constraint_matrix_Y)


#C_init = np.random.rand(varables*varables*window + varables*varables)
#not create no C_init with XYset less variables and instread enforce in loss func
#to avoid unnessasary copying

2
0.0
1.1
1
6.0


In [72]:
def enforce_cons(X, cons):
    for (i, j, val) in cons:
        X[i][j] = val

def f_DYNOTEARS_CONSTRAINT(X, Y, lA, lB, X_cons, Y_cons):
    def aux(C):
        w = C[varables*window*varables:].reshape(varables, varables)
        enforce_cons(w, X_cons)
        a = C[:varables*window*varables].reshape(varables, varables*window)
        enforce_cons(a, Y_cons)
    
        loss = np.square(
                np.linalg.norm(
                    np.matmul(np.eye(varables, varables) - w, X)
                    - np.matmul(a, Y)
                    , "fro"
                )
            )/np.prod(X.shape)
        #print(loss)
        return loss + lB*np.linalg.norm(w.flatten(), 1) + lA*np.linalg.norm(a.flatten(), 1) 
    return aux

In [73]:
def constr_DYNOTEARS(C):
    w = C[varables*window*varables:].reshape(varables, varables)
    return qDag(w)

cons = {'type':'eq', 'fun': constr_DYNOTEARS}

C = sc.optimize.minimize(f_DYNOTEARS_CONSTRAINT(X,Y,.1,.1,X_sparce, Y_sparce) , C_init, constraints=cons).x

In [74]:

W = C[varables*window*varables:].reshape(varables, varables)
enforce_cons(W, X_sparce)
A = C[:varables*window*varables].reshape(varables, varables*window)
enforce_cons(A, Y_sparce)
np.fill_diagonal(W, 0)

In [75]:
enforce_cons(A, Y_sparce)
A.round(1)

array([[ 0. ,  0. ,  0. ,  0. ,  1.2,  0. ],
       [-0.4, -0.3, -0.4,  6. , -3.3, -0.4],
       [ 0. ,  0. ,  0. , -0. , -1.1,  1.1]])

In [76]:
dagY.round(1)

array([[0. , 0. , 0. , 0. , 1.3, 0. ],
       [0. , 0. , 0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.3]])

In [77]:
W.round(1)

array([[ 0. ,  0.1,  0. ],
       [-0. ,  0. ,  0. ],
       [ 0. ,  1.1,  0. ]])

In [78]:
dagX.round(1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
#testing confounded in Y

varables = 3
observations = 1000
window = 3
#to use later 
times = 5
C_init = np.random.rand(varables*varables*window + varables*varables)

In [80]:
dagY = sc.sparse.random(varables, varables*window, density=0.15, data_rvs=get_r(.5)).A

dagX = np.eye(varables, varables)
    while qDag(dagX) != 0:
    dagX = sc.sparse.random(varables, varables, density=0.25, data_rvs=get_r(.5)).A
    np.fill_diagonal(dagX, 0)

In [81]:
for i in range(len(dagY)):
    dagY[i][i] = .2

In [82]:
Y_pre = np.ones(observations*varables*window).reshape(varables*window, observations)
XY = makeSynthData(Y_pre, times, observations, varables, 0, randFlat)
Y=XY[varables:window*varables+varables]
X=XY[:varables]

In [83]:
def f_DYNOTEARS(X, Y, lA, lB):
    def aux(C):
        a = C[:varables*window*varables].reshape(varables, varables*window)
        w = C[varables*window*varables:].reshape(varables, varables)
    
        loss = np.square(
                np.linalg.norm(
                    np.matmul(np.eye(varables, varables) - w, X)
                    - np.matmul(a, Y)
                    , "fro"
                )
            )/np.prod(X.shape)
        #print(loss)
        return loss + lB*np.linalg.norm(w.flatten(), 1) + lA*np.linalg.norm(a.flatten(), 1) 
    return aux

In [84]:
cons = {'type':'eq', 'fun': constr_DYNOTEARS}

C = sc.optimize.minimize(f_DYNOTEARS(X,Y,.1,.1) , C_init, constraints=cons).x
A = C[:varables*window*varables].reshape(varables, varables*window)
W = C[varables*window*varables:].reshape(varables, varables)


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/linalg/_matfuncs.py:378: RuntimeWarning: overflow encountered in matmul
  eAw = eAw @ eAw


In [85]:
W.round(1)

array([[ 0. , -0. ,  0.6],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0.3,  0. ]])

In [86]:
dagX.round(1)

array([[0. , 0. , 1.4],
       [0. , 0. , 1.4],
       [0. , 0. , 0. ]])

In [87]:
A.round(1)

array([[-0. , -0. , -0. , -0. ,  0.5,  0. , -0. ,  0. ,  0. ],
       [ 1.4,  0.2,  0. ,  0. ,  0. , -0. ,  0. ,  0.2,  0.3],
       [ 0. , -0. ,  0. ,  0. , -0. ,  0. , -0. , -0. , -0. ]])

In [88]:
dagY.round(1)

array([[0.2, 0. , 0. , 0. , 0.6, 0. , 0. , 0. , 0. ],
       [1.4, 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0.9],
       [0.5, 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. ]])