In [1]:
from src.data.dataset import Dataset
from src.utill.constraint import Constraint
from src.utill.WAgraph import WAgraph
from src.model.NOTEARS import NOTEARS
from src.trainer.trainer import Trainer
import numpy as np

In [139]:
observations = 3
variables = 2
times = 6
window = 4

In [140]:
cons = Constraint([], [], window, variables)

In [141]:
W = np.array([[]])
cons.constrainW(W)
W

array([], shape=(1, 0), dtype=float64)

In [142]:
cons = Constraint([[0,0,1], [1,0,3]], [[0,0,0,1]], window, variables)

In [143]:
W = np.array([[2, 2],[2, 2]])
cons.constrainW(W)
W

array([[1, 2],
       [3, 2]])

In [144]:
A = np.array([[[2], [2]],[[2], [2]]])
cons.constrainA(A)
A

array([[[1],
        [2]],

       [[2],
        [2]]])

In [145]:
cons.validate(window, variables)

True

In [146]:
WA = WAgraph(window, variables)

In [147]:
WA.getWindow()

4

In [148]:
WA.getV()

2

In [149]:
WA.getVA()

2

In [150]:
WA.setW([[2,2],[2,2]])
WA.getW()

array([[2, 2],
       [2, 2]])

In [151]:
WA.setA([[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]])
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [152]:
WA.generateW()

In [153]:
WA.getW()

array([[0.42077553, 0.12635419],
       [0.5133799 , 0.15976728]], dtype=float32)

In [154]:
WA.generateW_B(1, 'ER')

2 1


In [155]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [156]:
WA.generateW()
WA.getW()

array([[0.        , 0.        ],
       [0.79977524, 0.        ]], dtype=float32)

In [157]:
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [158]:
WA.A_B

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int32)

In [159]:
WA.generateA()
WA.getA()

array([[[0.8630755 , 0.66960305],
        [0.7496601 , 0.7030773 ]],

       [[0.01844579, 0.41253522],
        [0.23764223, 0.4633031 ]],

       [[0.9112983 , 0.7981976 ],
        [0.6926623 , 0.8043077 ]],

       [[0.17468293, 0.20105241],
        [0.4861069 , 0.6002657 ]]], dtype=float32)

In [160]:
WA.generateA_B(3, 'ER')

In [161]:
WA.A_B

tensor([[[0., 1.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.]]], dtype=torch.float64)

In [162]:
WA.generateA()
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [163]:
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [164]:
WA.getW()

array([[0.        , 0.        ],
       [0.79977524, 0.        ]], dtype=float32)

In [165]:
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [166]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [167]:
WA.A_B

tensor([[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [1, 0]]], dtype=torch.int32)

In [168]:
from src.data.dataset import Dataset

In [169]:
ds = Dataset(observations, variables, variables, times, window, WA, cons)

In [170]:
dataex = np.array([[[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]]])

ds.setData(dataex)

In [171]:
ds.getData()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [172]:
ds.getDataWindow()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [173]:
ds.getWA()

In [174]:
ds.generateData(lambda x: np.random.rand())

In [175]:
ds.data

array([[[6.19308599, 9.676685  , 6.67315119],
        [5.09300776, 9.54586462, 6.3568389 ]],

       [[5.38919112, 7.45415205, 5.63325872],
        [5.31682989, 6.10664276, 5.38664944]],

       [[4.49378209, 6.89280399, 4.33145023],
        [4.00041544, 7.6830784 , 5.22637904]],

       [[4.37258451, 4.874131  , 3.05829567],
        [4.1480065 , 4.89110079, 2.61573823]],

       [[3.25025432, 3.53964764, 2.41048022],
        [3.66181414, 3.45657914, 2.21467271]],

       [[1.74097841, 2.05275194, 1.33495097],
        [3.20029217, 3.0310054 , 2.99239973]]])

In [176]:
ds.WA.A

tensor([[[1.0000, 0.3965],
         [0.0000, 0.0000]],

        [[0.0000, 0.5353],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.1274, 0.0000]]], dtype=torch.float64)

In [177]:
ds.WA.W

tensor([[1., 0.],
        [3., 0.]])

In [178]:
ds.WA.getW()

array([[1., 0.],
       [3., 0.]], dtype=float32)

In [179]:
import math
pos = np.random.randint(0, (2*2-2)//2)
y = math.floor(.5*(np.sqrt(8*pos+9)))
x = pos-(y*(y-1)//2)
print(pos)
print(y)
print(x)

0
1
0


In [180]:
ds.WA.getW()[y][x]

3.0

In [181]:
WA.generateW_B(1, "ER")
WA.generateW()

2 1


In [182]:
WA.getW()

array([[0.        , 0.        ],
       [0.18188666, 0.        ]], dtype=float32)

In [183]:
WA.getW_B()

array([[0, 0],
       [1, 0]])

In [184]:
nt = NOTEARS(window, variables)

In [185]:
nt.set_learning_rate(1e-3)

In [186]:
nt.run(ds.data)

(tensor(222.6634, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(222.6634, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [187]:
nt.update(ds.data)

/Users/tylergibbs/dsc180/src/model/model.py:60: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


(tensor(222.6634, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(222.6634, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [188]:
nt.WA.W.grad

tensor([[-235.3647, -221.7785],
        [-221.7785, -209.9622]])

In [240]:
observations = 10000
variables = 3
times = 2
window = 1

WA = WAgraph(window, variables)
WA.generateW_B(1, 'ER')
WA.generateW(lambda: np.random.rand()+2)
WA.generateA_B(0, 'ER')
WA.generateA(lambda: np.random.rand()+1)

cons = Constraint([], [], window, variables)

ds = Dataset(observations, variables, variables, times, window, WA, cons)
ds.generateData(lambda x: np.random.rand())

nt = NOTEARS(window, variables, .05, .05, 1000)

tr = Trainer(.1)
tr.train(nt, ds.data, ds.data, 10000, 0, 1000)

3 1
TRAINING: [Iter 0] score 8.28359317779541, likelyhood 8.28359317779541, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0
(0, 'VALIDATION: [Iter 0] score 8.28359317779541, likelyhood 8.28359317779541, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0')
TRAINING: [Iter 1000] score 0.6127249598503113, likelyhood 0.3845727741718292, sparcityW 4.073526382446289, sparcityA 0.4847496449947357, acyclicity 2.384185791015625e-07
(1000, 'VALIDATION: [Iter 1000] score 0.612471878528595, likelyhood 0.3845727741718292, sparcityW 4.073526382446289, sparcityA 0.4847496449947357, acyclicity 2.384185791015625e-07')
TRAINING: [Iter 2000] score 0.6725935935974121, likelyhood 0.3689410388469696, sparcityW 4.3821797370910645, sparcityA 0.4987782835960388, acyclicity 5.9604644775390625e-05
(2000, 'VALIDATION: [Iter 2000] score 0.6963778734207153, likelyhood 0.3689410388469696, sparcityW 4.3821797370910645, sparcityA 0.4987782835960388, acyclicity 5.9604644775390625e-05')
TRAINING: [Iter 3000] score 0.637093484401

In [241]:
nt.WA.getW().round(2)

array([[ 0.  ,  0.  , -0.  ],
       [ 0.83, -0.  ,  0.59],
       [ 2.56, -0.  , -0.  ]], dtype=float32)

In [242]:
ds.WA.getW()

array([[0.       , 0.       , 0.       ],
       [2.5096433, 0.       , 0.       ],
       [2.760073 , 0.       , 0.       ]], dtype=float32)

In [243]:
nt.WA.getA().round(1)

array([[[ 0. ,  0. , -0. ],
        [ 0.1,  0.1,  0.1],
        [ 0.1,  0. ,  0.1]]], dtype=float32)

In [244]:
ds.WA.getA().round(1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])