In [335]:
from src.data.dataset import Dataset
from src.utill.constraint import Constraint
from src.utill.WAgraph import WAgraph
from src.model.NOTEARS import NOTEARS
from src.model.DAGMA import DAGMA
from src.trainer.trainer import Trainer
import numpy as np

In [139]:
observations = 3
variables = 2
times = 6
window = 4

In [140]:
cons = Constraint([], [], window, variables)

In [141]:
W = np.array([[]])
cons.constrainW(W)
W

array([], shape=(1, 0), dtype=float64)

In [142]:
cons = Constraint([[0,0,1], [1,0,3]], [[0,0,0,1]], window, variables)

In [143]:
W = np.array([[2, 2],[2, 2]])
cons.constrainW(W)
W

array([[1, 2],
       [3, 2]])

In [144]:
A = np.array([[[2], [2]],[[2], [2]]])
cons.constrainA(A)
A

array([[[1],
        [2]],

       [[2],
        [2]]])

In [145]:
cons.validate(window, variables)

True

In [146]:
WA = WAgraph(window, variables)

In [147]:
WA.getWindow()

4

In [148]:
WA.getV()

2

In [149]:
WA.getVA()

2

In [150]:
WA.setW([[2,2],[2,2]])
WA.getW()

array([[2, 2],
       [2, 2]])

In [151]:
WA.setA([[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]],[[2,2],[2,2]]])
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [152]:
WA.generateW()

In [153]:
WA.getW()

array([[0.42077553, 0.12635419],
       [0.5133799 , 0.15976728]], dtype=float32)

In [154]:
WA.generateW_B(1, 'ER')

2 1


In [155]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [156]:
WA.generateW()
WA.getW()

array([[0.        , 0.        ],
       [0.79977524, 0.        ]], dtype=float32)

In [157]:
WA.getA()

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [158]:
WA.A_B

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int32)

In [159]:
WA.generateA()
WA.getA()

array([[[0.8630755 , 0.66960305],
        [0.7496601 , 0.7030773 ]],

       [[0.01844579, 0.41253522],
        [0.23764223, 0.4633031 ]],

       [[0.9112983 , 0.7981976 ],
        [0.6926623 , 0.8043077 ]],

       [[0.17468293, 0.20105241],
        [0.4861069 , 0.6002657 ]]], dtype=float32)

In [160]:
WA.generateA_B(3, 'ER')

In [161]:
WA.A_B

tensor([[[0., 1.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.]]], dtype=torch.float64)

In [162]:
WA.generateA()
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [163]:
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [164]:
WA.getW()

array([[0.        , 0.        ],
       [0.79977524, 0.        ]], dtype=float32)

In [165]:
WA.getA()

array([[[0.        , 0.39647606],
        [0.        , 0.        ]],

       [[0.        , 0.53526437],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [0.12735143, 0.        ]]])

In [166]:
WA.W_B

tensor([[0, 0],
        [1, 0]])

In [167]:
WA.A_B

tensor([[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [1, 0]]], dtype=torch.int32)

In [168]:
from src.data.dataset import Dataset

In [169]:
ds = Dataset(observations, variables, variables, times, window, WA, cons)

In [170]:
dataex = np.array([[[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]],
                   [[1,2,3],[4,5,6]]])

ds.setData(dataex)

In [171]:
ds.getData()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [172]:
ds.getDataWindow()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [173]:
ds.getWA()

In [174]:
ds.generateData(lambda x: np.random.rand())

In [175]:
ds.data

array([[[6.19308599, 9.676685  , 6.67315119],
        [5.09300776, 9.54586462, 6.3568389 ]],

       [[5.38919112, 7.45415205, 5.63325872],
        [5.31682989, 6.10664276, 5.38664944]],

       [[4.49378209, 6.89280399, 4.33145023],
        [4.00041544, 7.6830784 , 5.22637904]],

       [[4.37258451, 4.874131  , 3.05829567],
        [4.1480065 , 4.89110079, 2.61573823]],

       [[3.25025432, 3.53964764, 2.41048022],
        [3.66181414, 3.45657914, 2.21467271]],

       [[1.74097841, 2.05275194, 1.33495097],
        [3.20029217, 3.0310054 , 2.99239973]]])

In [176]:
ds.WA.A

tensor([[[1.0000, 0.3965],
         [0.0000, 0.0000]],

        [[0.0000, 0.5353],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.1274, 0.0000]]], dtype=torch.float64)

In [177]:
ds.WA.W

tensor([[1., 0.],
        [3., 0.]])

In [178]:
ds.WA.getW()

array([[1., 0.],
       [3., 0.]], dtype=float32)

In [179]:
import math
pos = np.random.randint(0, (2*2-2)//2)
y = math.floor(.5*(np.sqrt(8*pos+9)))
x = pos-(y*(y-1)//2)
print(pos)
print(y)
print(x)

0
1
0


In [180]:
ds.WA.getW()[y][x]

3.0

In [181]:
WA.generateW_B(1, "ER")
WA.generateW()

2 1


In [182]:
WA.getW()

array([[0.        , 0.        ],
       [0.18188666, 0.        ]], dtype=float32)

In [183]:
WA.getW_B()

array([[0, 0],
       [1, 0]])

In [184]:
nt = NOTEARS(window, variables)

In [185]:
nt.set_learning_rate(1e-3)

In [186]:
nt.run(ds.data)

(tensor(222.6634, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(222.6634, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [187]:
nt.update(ds.data)

/Users/tylergibbs/dsc180/src/model/model.py:60: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


(tensor(222.6634, grad_fn=<AddBackward0>),
 {'likelyhood': tensor(222.6634, grad_fn=<DivBackward0>),
  'sparcityW': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'sparcityA': tensor(0., grad_fn=<LinalgVectorNormBackward0>),
  'acyclicity': tensor(0., grad_fn=<SubBackward0>)})

In [188]:
nt.WA.W.grad

tensor([[-235.3647, -221.7785],
        [-221.7785, -209.9622]])

In [333]:
observations = 10000
variables = 3
times = 2
window = 1

WA = WAgraph(window, variables)
WA.generateW_B(1, 'ER')
WA.generateW(lambda: np.random.rand()+.5)
WA.generateA_B(2, 'ER')
WA.generateA(lambda: np.random.rand()+.5)

cons = Constraint([], [], window, variables)
ds = Dataset(observations, variables, variables, times, window, WA, cons)
ds.generateData(lambda x: np.random.rand())
tr = Trainer(.1)

3 1


In [334]:
WA.W

tensor([[0.0000, 0.0000, 0.0000],
        [0.5052, 0.0000, 0.0000],
        [0.0000, 1.2609, 0.0000]])

In [328]:
nt = NOTEARS(window, variables, .05, .05, 100)

tr.train(nt, ds.data, ds.data, 10000, 0, 1000)

3 1
TRAINING: [Iter 0] score 3.164108991622925, likelyhood 3.164108991622925, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0
(0, 'VALIDATION: [Iter 0] score 3.164108991622925, likelyhood 3.164108991622925, sparcityW 0.0, sparcityA 0.0, acyclicity 0.0')
TRAINING: [Iter 1000] score 0.5542342066764832, likelyhood 0.389293372631073, sparcityW 2.1675057411193848, sparcityA 1.1027010679244995, acyclicity 1.430511474609375e-05
(1000, 'VALIDATION: [Iter 1000] score 0.5543432235717773, likelyhood 0.389293372631073, sparcityW 2.1675057411193848, sparcityA 1.1027010679244995, acyclicity 1.430511474609375e-05')
TRAINING: [Iter 2000] score 0.5548948645591736, likelyhood 0.3904722332954407, sparcityW 2.1309211254119873, sparcityA 1.1293987035751343, acyclicity 1.4066696166992188e-05
(2000, 'VALIDATION: [Iter 2000] score 0.5544917583465576, likelyhood 0.3904722332954407, sparcityW 2.1309211254119873, sparcityA 1.1293987035751343, acyclicity 1.4066696166992188e-05')
TRAINING: [Iter 3000] score 0.5584366

In [329]:
nt.WA.getW().round(2)

array([[ 0.  ,  0.  ,  0.01],
       [ 1.29, -0.  ,  0.5 ],
       [ 0.33,  0.01,  0.  ]], dtype=float32)

In [330]:
ds.WA.getW()

array([[0.       , 0.       , 0.       ],
       [1.4283786, 0.       , 0.       ],
       [0.       , 0.9306136, 0.       ]], dtype=float32)

In [331]:
nt.WA.getA().round(1)

array([[[-0. , -0. ,  0. ],
        [ 0.2,  0. ,  0.3],
        [ 0.2,  0. ,  0.3]]], dtype=float32)

In [332]:
ds.WA.getA().round(1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

3 1


In [301]:
WA.getW().round(2)

array([[0.  , 0.  , 0.  , 0.  ],
       [2.85, 0.  , 0.  , 0.  ],
       [2.63, 0.  , 0.  , 0.  ],
       [0.  , 2.16, 0.  , 0.  ]], dtype=float32)

In [287]:
WA.getA().round(1)

array([[[0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 1.6, 0. , 0. ],
        [0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 1.8]]])

In [336]:
nt = DAGMA(window, variables, .05, .05, 100)

tr.train(nt, ds.data, ds.data, 10000, 0, 1000)

TRAINING: [Iter 0] score -57.22974395751953, likelyhood 12.084976196289062, sparcityW 0.0, sparcityA 0.0, acyclicity -0.6931471824645996
(0, 'VALIDATION: [Iter 0] score -57.22974395751953, likelyhood 12.084976196289062, sparcityW 0.0, sparcityA 0.0, acyclicity -0.6931471824645996')
TRAINING: [Iter 1000] score -68.71855163574219, likelyhood 0.34593531489372253, sparcityW 1.3304551839828491, sparcityA 3.6040589809417725, acyclicity -0.6931121349334717
(1000, 'VALIDATION: [Iter 1000] score -68.71966552734375, likelyhood 0.34593531489372253, sparcityW 1.3304551839828491, sparcityA 3.6040589809417725, acyclicity -0.6931121349334717')
TRAINING: [Iter 2000] score -68.71419525146484, likelyhood 0.35258030891418457, sparcityW 1.3109709024429321, sparcityA 3.6076130867004395, acyclicity -0.6931270360946655
(2000, 'VALIDATION: [Iter 2000] score -68.7137451171875, likelyhood 0.35258030891418457, sparcityW 1.3109709024429321, sparcityA 3.6076130867004395, acyclicity -0.6931270360946655')
TRAINING: 

In [337]:
nt.WA.getW().round(2)

array([[0.01, 0.  , 0.  ],
       [0.5 , 0.  , 0.  ],
       [0.  , 0.8 , 0.  ]], dtype=float32)

In [338]:
ds.WA.getW().round(2)

array([[0.  , 0.  , 0.  ],
       [0.51, 0.  , 0.  ],
       [0.  , 1.26, 0.  ]], dtype=float32)

In [339]:
nt.WA.getA().round(1)

array([[[ 0. ,  0. ,  1.2],
        [ 0.1,  0.1,  0. ],
        [ 0.1,  1.3, -0.7]]], dtype=float32)

In [340]:
ds.WA.getA().round(1)

array([[[0. , 0. , 1.3],
        [0. , 0. , 0. ],
        [0. , 1.2, 0. ]]])