In [1]:
import numpy as np
import scipy.linalg as sla
import numpy.linalg as la
from scipy.special import expit as sigmoid
import scipy as sc


In [2]:
varables = 3
observations = 20
window = 5
varTime = varables*window

#to use later 
#times = 10
#splObs = observations*(times-window)

In [3]:
dag = sc.sparse.random(varables*window, varables, density=0.15).A

In [4]:
dag.round(2)

array([[0.26, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.87, 0.  ],
       [0.94, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.21],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.79, 0.  ],
       [0.09, 0.53, 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [5]:
A_init = np.random.rand(varables*varables*window).reshape(varables*window, varables)

#later
#W = np.random.rand(varables*observations).reshape(varables,observations)

In [6]:
Y = np.random.rand(observations*varables*window).reshape(observations, varables*window)


In [13]:
#X = XW + YA + Z

X_firm = np.matmul(Y, dag) 

X_rand = X_firm + np.random.normal(0, X_firm.std()/6, X_firm.shape)

In [8]:
def f(X):
    def aux(A):
        a = A.reshape(varables*window, varables)
    
        xp = np.matmul(Y, a)
    
        dif = (X - xp)
    
        return (dif * dif).sum()
    return aux

In [9]:
A = sc.optimize.minimize(f(X_firm) , A_init).x.reshape(varables*window, varables)

/var/folders/z_/p0tz320d6j13q0rkv_f35brm0000gn/T/ipykernel_7810/1142828865.py:1: DeprecationWarning: Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions will be removed from `x0`, but an error will be raised in SciPy 1.11.0.
  A = sc.optimize.minimize(f(X_firm) , A_init).x.reshape(varables*window, varables)


In [10]:
(A-dag).round(2)

array([[-0., -0.,  0.],
       [ 0.,  0.,  0.],
       [ 0., -0.,  0.],
       [-0., -0.,  0.],
       [-0., -0., -0.],
       [-0.,  0., -0.],
       [ 0.,  0., -0.],
       [ 0.,  0., -0.],
       [ 0.,  0.,  0.],
       [-0., -0.,  0.],
       [ 0.,  0.,  0.],
       [ 0., -0., -0.],
       [ 0.,  0.,  0.],
       [-0.,  0., -0.],
       [ 0.,  0., -0.]])

In [14]:
A = sc.optimize.minimize(f(X_rand) , A_init).x.reshape(varables*window, varables)

/var/folders/z_/p0tz320d6j13q0rkv_f35brm0000gn/T/ipykernel_7810/732214466.py:1: DeprecationWarning: Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions will be removed from `x0`, but an error will be raised in SciPy 1.11.0.
  A = sc.optimize.minimize(f(X_rand) , A_init).x.reshape(varables*window, varables)


In [16]:
A.round(1)

array([[ 0.3, -0. , -0.1],
       [ 0. ,  0.3,  0. ],
       [-0. , -0.3,  0. ],
       [-0.2,  0.9,  0.1],
       [ 0.9, -0.1,  0. ],
       [-0.1,  0.2,  0. ],
       [ 0.1, -0. ,  0.1],
       [ 0.1,  0.1,  0.2],
       [ 0. ,  0.1,  0. ],
       [-0. , -0.1,  0. ],
       [ 0. ,  0.1,  0. ],
       [-0.1,  0.7, -0.1],
       [ 0.1,  0.3, -0.1],
       [ 0.1, -0. , -0. ],
       [ 0.1,  0. ,  0.1]])

In [17]:
dag.round(1)

array([[0.3, 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0.9, 0. ],
       [0.9, 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0.2],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0.8, 0. ],
       [0.1, 0.5, 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ]])